### ISSUE TITLE
Log implementation for hcx-integrator-sdk

### ISSUE THREAD

**Issue by sanjitvimal** [Swasth-Digital-Health-Foundation/hcx-platform#374]
Requesting team to implement logger in hcx-integrator-sdk . which is going to boost the integration process. Level of logs need to define strategically.

Current issue:- Code is throwing exception while processing incoming response but root cause is not logged.
Response during decryption -  Error Code::ERR_INVALID_ENCRYPTION, Message::null

Sample code:-  
Class - io.hcxprotocol.impl.HCXIncomingRequest.java
private static final org.slf4j.Logger log= org.slf4j.LoggerFactory.getLogger(HCXIncomingRequest.class);

public boolean **decryptPayload**(String jwePayload, Map<String, Object> output) {
.
.
.
catch (Exception var4) {
            **log.error("Error in decryption {}", var4);**
            output.put(ErrorCodes.ERR_INVALID_ENCRYPTION.toString(), var4.getMessage());
            return false;
        }
    }

**Comment by shiva-rakshith** [comment]
Hi @sanjitvimal 

We have enhanced the loggers in hcx-integrator-sdk v1.0.3. Please find the maven dependency link below:
https://central.sonatype.com/artifact/io.hcxprotocol/hcx-integrator-sdk/1.0.3/overview

Thanks,
Rakshith.
